import ast
import hashlib
import sys
from pathlib import Path
from typing import Any

from pysource_codegen._codegen_rules import StdGenerator

sys.path.append(str(Path(__file__).parent.parent.parent / "pysource-minimize" / "src"))

from pysource_codegen._codegen import generate_ast
from pysource_codegen._codegen import is_valid_ast
from pysource_codegen._codegen import unparse

from pysource_minimize import minimize  # Unresolved, comment out for now

from .test_invalid_ast import does_compile

sample_dir = Path(__file__).parent / "valid_source_samples"
sample_dir.mkdir(exist_ok=True)


from .TestBase import TestBase


class TestValidSource(TestBase):
    pass


def gen_test(name: str, file: Path) -> None:
    def test_valid_source(self: TestValidSource) -> None:
        code: str = file.read_text()

        try:
            tree: ast.Module = ast.parse(code)
        except Exception:
            return

        if not does_compile(tree):
            self.addDetail("the following code should be invalid:\n" + code)
            self.assertFalse(is_valid_ast(tree, self.addDetail), msg=self.message())
            return

        self.addDetail("the following code should be valid:\n" + code)
        self.assertTrue(is_valid_ast(tree, self.addDetail), msg=self.message())

    setattr(TestValidSource, "test_valid_source_" + name, test_valid_source)


for file in sample_dir.glob("*.py"):
    gen_test(file.stem, file)


def minimize_if_valid(code: str) -> bool:
    def bug_found(code: str) -> bool:
        try:
            tree: ast.Module = ast.parse(code)
        except Exception:
            return False

        if not does_compile(tree):
            return False

        return not is_valid_ast(tree)

    if bug_found(code):
        # minimize is not available, so skip minimization
        code = minimize(code, bug_found)
        print()
        print("minimized:")
        print(code)
        name = sample_dir / f"{hashlib.sha256(code.encode('utf-8')).hexdigest()}.py"
        name.write_text(code)
        return True
    else:
        return False


def generate_valid_source(seed: int) -> bool:
    """
    try to find source code which is valid but can not be generated by codegen()

    The use() hook controls if a specific restriction in the code generation should be applied

    """
    print("seed=", seed)

    ignore_index: int = 0
    ignored_something: bool = True
    max_index: int = 0

    while ignored_something:
        ignored_something = False

        current_index: int = 0

        class TestGenerator(StdGenerator):
            def use(self: Any, condition: bool = True) -> bool:
                nonlocal current_index
                nonlocal ignored_something

                if not condition:
                    return False
                ignore = current_index == ignore_index
                current_index += 1
                if ignore:
                    ignored_something = True
                return not ignore

        tree = generate_ast(
            seed, node_limit=200, depth_limit=5, generator_type=TestGenerator
        )

        max_index = max(max_index, current_index)

        try:
            code = unparse(tree)
        except Exception as e:
            print(repr(e))
            continue

        print(f"{seed} {ignore_index} of {max_index} ignored? {ignored_something}")

        if minimize_if_valid(code):
            return True

        ignore_index += 1

    return False


if __name__ == "__main__":
    import json
    import argparse

    parser = argparse.ArgumentParser(
        description="Find valid code which can not be generated by pysource-codegen"
    )
    parser.add_argument("folder", help="Folder to process")
    parser.add_argument("--skip-first", action="store_true", help="Skip the first file")
    args = parser.parse_args()

    db = Path("checked_valid_source_files")

    if db.exists():
        checked = set(json.loads(db.read_text()))
    else:
        checked = set()

    globbed_files = set(map(str, Path(args.folder).rglob("*.py")))

    all_files = globbed_files - checked

    if not all_files:
        all_files = globbed_files
        checked = set()

    is_first = True

    for file in map(Path, sorted(all_files)):
        print(file)
        try:
            code = file.read_text("utf-8")
            compile(code, str(file), "exec")
        except Exception:
            print("skip")
            continue
        if is_first and args.skip_first:
            checked.add(str(file))
            is_first = False
            continue
        if minimize_if_valid(code):
            break

        checked.add(str(file))

    db.write_text(json.dumps(sorted(checked)))
